spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaobao?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 158188
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/templates/,classpath:/static/

  redis:
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006