spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaobao?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 158188
    driver-class-name: com.mysql.jdbc.Driver
